-- The schema every database reaches by the point golang-migrate takes
-- over — generated by introspecting a fresh AutoMigrate run against
-- every model in db/legacy_migrations.go's autoMigrateModels (SELECT sql
-- FROM sqlite_master), not hand-transcribed from the Go struct tags, so
-- this is byte-for-byte what the last AutoMigrate-based release actually
-- created. An explicit, readable baseline of that schema, the same reason
-- a codebase migrating onto a real migration tool usually writes one —
-- see db/migrate.go's runMigrations for why this never actually does real
-- work in practice: its own legacy bridge (AutoMigrate, run once) always
-- brings a database fully current before this file ever runs, so its IF
-- NOT EXISTS clauses only ever see a schema that's already exactly this
-- one. It stays real, valid SQL regardless — a safety net if that bridge
-- is ever removed for a database with nothing but this to create it from.
--
-- sqlite_sequence (SQLite's own internal bookkeeping table for
-- AUTOINCREMENT columns) is deliberately not created here — SQLite
-- manages its existence itself the moment any AUTOINCREMENT table
-- exists; declaring it ourselves would be redundant at best.
--
-- Never edit this file once released, the same rule as every other
-- migration here — express a schema change as a new numbered migration
-- instead, even one that targets a table this file already creates.

CREATE TABLE IF NOT EXISTS `users` (`id` varchar(255) NOT NULL,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`email` text,`username` text,`picture` text,`name` text,`given_name` text,`family_name` text,`locale` text,`provider` text,`provider_id` text,`password` text,`password_reset` numeric,`password_reset_code` text,`password_reset_expires` datetime,`email_confirmed` numeric,`email_confirmation_code` text,`email_confirmation_expires` datetime,PRIMARY KEY (`id`),CONSTRAINT `uni_users_email` UNIQUE (`email`),CONSTRAINT `uni_users_username` UNIQUE (`username`));
CREATE INDEX IF NOT EXISTS `idx_users_deleted_at` ON `users`(`deleted_at`);

CREATE TABLE IF NOT EXISTS `sessions` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`token_hash` varchar(64) NOT NULL DEFAULT "",`user_id` varchar(255),`username` text,`email` text,`is_authenticated` numeric,`is_admin` numeric,`valid_until` datetime,`provider` text,`closed_on` datetime,`last_activity` datetime,`session_name` varchar(100),`created_from` varchar(100),`ip_address` varchar(45),`user_agent` text,`referrer` varchar(500),`browser_family` varchar(100),`browser_version` varchar(100),`os_family` varchar(100),`os_version` varchar(100),`device_family` varchar(100),`device_brand` varchar(100),`device_model` varchar(100),`geo_location` varchar(200),`latitude` decimal(10,8),`longitude` decimal(11,8),`city` varchar(100),`zip_code` varchar(20),`country` varchar(100),`country_code` varchar(3),`region` varchar(100),`continent` varchar(50),`fingerprint` varchar(100),`fingerprint_type` varchar(20));
CREATE INDEX IF NOT EXISTS `idx_sessions_deleted_at` ON `sessions`(`deleted_at`);
CREATE INDEX IF NOT EXISTS `idx_sessions_fingerprint` ON `sessions`(`fingerprint`);
CREATE INDEX IF NOT EXISTS `idx_sessions_ip_address` ON `sessions`(`ip_address`);

CREATE TABLE IF NOT EXISTS `traffic_metrics` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`http_method` varchar(10) NOT NULL,`path` varchar(500) NOT NULL,`http_status` integer NOT NULL,`response_time_ns` integer NOT NULL,`timestamp` datetime NOT NULL,`response_size` integer DEFAULT 0,`error` text,`user_id` varchar(255),`session_id` varchar(255),`is_static_asset` numeric NOT NULL DEFAULT false,`ip_address` varchar(45),`user_agent` text,`referrer` varchar(500),`browser_family` varchar(100),`browser_version` varchar(100),`os_family` varchar(100),`os_version` varchar(100),`device_family` varchar(100),`device_brand` varchar(100),`device_model` varchar(100),`geo_location` varchar(200),`latitude` decimal(10,8),`longitude` decimal(11,8),`city` varchar(100),`zip_code` varchar(20),`country` varchar(100),`country_code` varchar(3),`region` varchar(100),`continent` varchar(50),`fingerprint` varchar(100),`fingerprint_type` varchar(20));
CREATE INDEX IF NOT EXISTS `idx_traffic_metrics_deleted_at` ON `traffic_metrics`(`deleted_at`);
CREATE INDEX IF NOT EXISTS `idx_traffic_metrics_fingerprint` ON `traffic_metrics`(`fingerprint`);
CREATE INDEX IF NOT EXISTS `idx_traffic_metrics_ip_address` ON `traffic_metrics`(`ip_address`);
CREATE INDEX IF NOT EXISTS `idx_traffic_metrics_is_static_asset` ON `traffic_metrics`(`is_static_asset`);

CREATE TABLE IF NOT EXISTS `tokens` (`id` varchar(255) NOT NULL,`user_id` varchar(255) NOT NULL,`token_hash` varchar(255) NOT NULL,`name` varchar(100) NOT NULL,`is_active` numeric DEFAULT true,`expires_at` datetime,`usage_count` integer DEFAULT 0,`last_used_at` datetime,`scopes` text,`created_from` varchar(100),`revoked_at` datetime,`revoked_by` varchar(255),`created_at` datetime,`updated_at` datetime,`ip_address` varchar(45),`user_agent` text,`referrer` varchar(500),`browser_family` varchar(100),`browser_version` varchar(100),`os_family` varchar(100),`os_version` varchar(100),`device_family` varchar(100),`device_brand` varchar(100),`device_model` varchar(100),`geo_location` varchar(200),`latitude` decimal(10,8),`longitude` decimal(11,8),`city` varchar(100),`zip_code` varchar(20),`country` varchar(100),`country_code` varchar(3),`region` varchar(100),`continent` varchar(50),`fingerprint` varchar(100),`fingerprint_type` varchar(20),PRIMARY KEY (`id`));
CREATE INDEX IF NOT EXISTS `idx_tokens_fingerprint` ON `tokens`(`fingerprint`);
CREATE INDEX IF NOT EXISTS `idx_tokens_ip_address` ON `tokens`(`ip_address`);
CREATE INDEX IF NOT EXISTS `idx_tokens_token_hash` ON `tokens`(`token_hash`);

CREATE TABLE IF NOT EXISTS `counters` (`id` varchar(255) NOT NULL,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`user_id` varchar(255) NOT NULL,`counter_id` varchar(255) NOT NULL,`amount` integer NOT NULL,`balance_after` integer NOT NULL,`description` text NOT NULL,PRIMARY KEY (`id`),CONSTRAINT `fk_counters_user` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`));
CREATE INDEX IF NOT EXISTS `idx_counters_counter_id` ON `counters`(`counter_id`);
CREATE INDEX IF NOT EXISTS `idx_counters_deleted_at` ON `counters`(`deleted_at`);
CREATE INDEX IF NOT EXISTS `idx_counters_user_id` ON `counters`(`user_id`);

CREATE TABLE IF NOT EXISTS `blocked_clients` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`reason` varchar(30) NOT NULL,`path` varchar(500),`trigger_count` integer NOT NULL,`blocked_at` datetime NOT NULL,`blocked_until` datetime NOT NULL,`ip_address` varchar(45),`user_agent` text,`referrer` varchar(500),`browser_family` varchar(100),`browser_version` varchar(100),`os_family` varchar(100),`os_version` varchar(100),`device_family` varchar(100),`device_brand` varchar(100),`device_model` varchar(100),`geo_location` varchar(200),`latitude` decimal(10,8),`longitude` decimal(11,8),`city` varchar(100),`zip_code` varchar(20),`country` varchar(100),`country_code` varchar(3),`region` varchar(100),`continent` varchar(50),`fingerprint` varchar(100),`fingerprint_type` varchar(20));
CREATE INDEX IF NOT EXISTS `idx_blocked_clients_blocked_at` ON `blocked_clients`(`blocked_at`);
CREATE INDEX IF NOT EXISTS `idx_blocked_clients_deleted_at` ON `blocked_clients`(`deleted_at`);
CREATE INDEX IF NOT EXISTS `idx_blocked_clients_fingerprint` ON `blocked_clients`(`fingerprint`);
CREATE INDEX IF NOT EXISTS `idx_blocked_clients_ip_address` ON `blocked_clients`(`ip_address`);
CREATE INDEX IF NOT EXISTS `idx_blocked_clients_reason` ON `blocked_clients`(`reason`);

CREATE TABLE IF NOT EXISTS `notifications` (`id` varchar(255) NOT NULL,`user_id` varchar(255) NOT NULL,`batch_id` varchar(255) NOT NULL,`type` varchar(255) NOT NULL,`title` text NOT NULL,`body` text NOT NULL,`url` text,`metadata` text,`actions` text,`created_at` datetime,`read_at` datetime,`responded_action_id` text,`responded_at` datetime,`responded_via` text,`respond_token_hash` text,`respond_token_expires_at` datetime,PRIMARY KEY (`id`));
CREATE INDEX IF NOT EXISTS `idx_notifications_batch_id` ON `notifications`(`batch_id`);
CREATE INDEX IF NOT EXISTS `idx_notifications_user_id` ON `notifications`(`user_id`);

CREATE TABLE IF NOT EXISTS `notification_deliveries` (`id` varchar(255) NOT NULL,`notification_id` varchar(255) NOT NULL,`channel` varchar(50) NOT NULL,`status` varchar(50) NOT NULL,`error` text,`external_ref` text,`attempt_number` integer NOT NULL DEFAULT 1,`next_retry_at` datetime,`sent_at` datetime,`created_at` datetime,PRIMARY KEY (`id`));
CREATE INDEX IF NOT EXISTS `idx_notification_deliveries_next_retry_at` ON `notification_deliveries`(`next_retry_at`);
CREATE INDEX IF NOT EXISTS `idx_notification_deliveries_notification_id` ON `notification_deliveries`(`notification_id`);

CREATE TABLE IF NOT EXISTS `notification_channel_links` (`id` varchar(255) NOT NULL,`user_id` varchar(255) NOT NULL,`channel` varchar(50) NOT NULL,`external_id` varchar(255) NOT NULL,`created_at` datetime,PRIMARY KEY (`id`));
CREATE UNIQUE INDEX IF NOT EXISTS `idx_notification_channel_link_user_channel` ON `notification_channel_links`(`user_id`,`channel`);
CREATE INDEX IF NOT EXISTS `idx_notification_channel_links_external_id` ON `notification_channel_links`(`external_id`);

CREATE TABLE IF NOT EXISTS `notification_link_codes` (`code` varchar(255) NOT NULL,`user_id` varchar(255) NOT NULL,`channel` varchar(50) NOT NULL,`created_at` datetime,`expires_at` datetime,PRIMARY KEY (`code`));

CREATE TABLE IF NOT EXISTS `notification_preferences` (`user_id` varchar(255) NOT NULL,`preferred_channel` varchar(50),`created_at` datetime,`updated_at` datetime,PRIMARY KEY (`user_id`));
