package gateway

import (
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/jmaister/taronja-gateway/config"
	"github.com/jmaister/taronja-gateway/static"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func boolPtr(b bool) *bool {
	return &b
}

func TestRobotsTxtAutoGenerated(t *testing.T) {
	tests := []struct {
		name           string
		routes         []config.RouteConfig
		expectedStatus int
		expectedBody   string
	}{
		{
			name:           "No robots config - default allow all",
			routes:         []config.RouteConfig{},
			expectedStatus: http.StatusOK,
			expectedBody:   "User-agent: *\nDisallow:\n",
		},
		{
			name: "Routes without robots field - default allow all",
			routes: []config.RouteConfig{
				{Name: "API", From: "/api/*", To: "http://localhost:8081"},
			},
			expectedStatus: http.StatusOK,
			expectedBody:   "User-agent: *\nDisallow:\n",
		},
		{
			name: "Single disallow route",
			routes: []config.RouteConfig{
				{Name: "API", From: "/api/*", To: "http://localhost:8081", Robots: boolPtr(false)},
			},
			expectedStatus: http.StatusOK,
			expectedBody:   "User-agent: *\nDisallow: /api/\n",
		},
		{
			name: "Single allow route",
			routes: []config.RouteConfig{
				{Name: "Public", From: "/public/*", To: "http://localhost:8081", Robots: boolPtr(true)},
			},
			expectedStatus: http.StatusOK,
			expectedBody:   "User-agent: *\nAllow: /public/\n",
		},
		{
			name: "Mix of allow and disallow routes",
			routes: []config.RouteConfig{
				{Name: "API", From: "/api/*", To: "http://localhost:8081", Robots: boolPtr(false)},
				{Name: "Admin", From: "/admin/*", To: "http://localhost:8081", Robots: boolPtr(false)},
				{Name: "Public", From: "/public/*", To: "http://localhost:8081", Robots: boolPtr(true)},
				{Name: "Unset", From: "/other/*", To: "http://localhost:8081"},
			},
			expectedStatus: http.StatusOK,
			expectedBody:   "User-agent: *\nDisallow: /api/\nDisallow: /admin/\nAllow: /public/\n",
		},
		{
			name: "Single file route with disallow",
			routes: []config.RouteConfig{
				{Name: "Favicon", From: "/favicon.ico", ToFile: "/tmp/favicon.ico", Static: true, Robots: boolPtr(false)},
			},
			expectedStatus: http.StatusOK,
			expectedBody:   "User-agent: *\nDisallow: /favicon.ico\n",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := &config.GatewayConfig{
				Server: config.ServerConfig{
					Host: "localhost",
					Port: 8080,
				},
				Management: config.ManagementConfig{
					Prefix: "/_",
				},
				Routes: tt.routes,
			}

			gw, err := NewTestGateway(cfg, &static.StaticAssetsFS)
			require.NoError(t, err)

			req := httptest.NewRequest("GET", "/robots.txt", nil)
			rr := httptest.NewRecorder()
			gw.Mux.ServeHTTP(rr, req)

			assert.Equal(t, tt.expectedStatus, rr.Code)
			assert.Equal(t, tt.expectedBody, rr.Body.String())
		})
	}
}

func TestRobotsTxtStaticFile(t *testing.T) {
	// Create a temporary robots.txt file
	tempDir := t.TempDir()
	robotsContent := "User-agent: *\nDisallow: /private/\nAllow: /\n"
	robotsFile := filepath.Join(tempDir, "robots.txt")
	err := os.WriteFile(robotsFile, []byte(robotsContent), 0644)
	require.NoError(t, err)

	cfg := &config.GatewayConfig{
		Server: config.ServerConfig{
			Host: "localhost",
			Port: 8080,
		},
		Management: config.ManagementConfig{
			Prefix: "/_",
		},
		Robots: config.RobotsConfig{
			File: robotsFile,
		},
		Routes: []config.RouteConfig{
			// Even with routes that have robots settings, the static file takes precedence
			{Name: "API", From: "/api/*", To: "http://localhost:8081", Robots: boolPtr(false)},
		},
	}

	gw, err := NewTestGateway(cfg, &static.StaticAssetsFS)
	require.NoError(t, err)

	req := httptest.NewRequest("GET", "/robots.txt", nil)
	rr := httptest.NewRecorder()
	gw.Mux.ServeHTTP(rr, req)

	assert.Equal(t, http.StatusOK, rr.Code)
	assert.Equal(t, robotsContent, rr.Body.String())
}

func TestGenerateRobotsTxt(t *testing.T) {
	tests := []struct {
		name     string
		routes   []config.RouteConfig
		expected string
	}{
		{
			name:     "empty routes",
			routes:   []config.RouteConfig{},
			expected: "User-agent: *\nDisallow:\n",
		},
		{
			name: "wildcard route disallowed",
			routes: []config.RouteConfig{
				{From: "/api/*", Robots: boolPtr(false)},
			},
			expected: "User-agent: *\nDisallow: /api/\n",
		},
		{
			name: "wildcard route allowed",
			routes: []config.RouteConfig{
				{From: "/public/*", Robots: boolPtr(true)},
			},
			expected: "User-agent: *\nAllow: /public/\n",
		},
		{
			name: "exact path disallowed",
			routes: []config.RouteConfig{
				{From: "/secret", Robots: boolPtr(false)},
			},
			expected: "User-agent: *\nDisallow: /secret\n",
		},
		{
			name: "nil robots skipped",
			routes: []config.RouteConfig{
				{From: "/api/*", Robots: nil},
			},
			expected: "User-agent: *\nDisallow:\n",
		},
		{
			name: "mixed routes",
			routes: []config.RouteConfig{
				{From: "/api/*", Robots: boolPtr(false)},
				{From: "/public/*", Robots: boolPtr(true)},
				{From: "/other/*", Robots: nil},
			},
			expected: "User-agent: *\nDisallow: /api/\nAllow: /public/\n",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := generateRobotsTxt(tt.routes)
			assert.Equal(t, tt.expected, result)
			assert.True(t, strings.HasPrefix(result, "User-agent: *\n"), "robots.txt should start with User-agent")
		})
	}
}
