name: "Go Cover Treemap Release"
description: "Runs Go coverage, generates a treemap SVG, and uploads it to a GitHub Release."
inputs:
  go-version:
    description: "The Go version to use"
    default: "1.22"
    required: false
  cover-args:
    description: "Arguments for go test -coverprofile"
    default: "./..."
    required: false
  treemap-output:
    description: "Output SVG file name"
    default: "coverage-treemap.svg"
    required: false
runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}

    - name: Run Go tests and generate coverage profile
      shell: bash
      run: go test -coverprofile=cover.out ${{ inputs.cover-args }}

    - name: Install go-cover-treemap
      shell: bash
      run: go install github.com/nikolaydubina/go-cover-treemap@latest

    - name: Generate SVG treemap
      shell: bash
      run: |
        go-cover-treemap --coverprofile=cover.out --output=${{ inputs.treemap-output }}

    - name: Upload SVG to Release (if in release context)
      uses: softprops/action-gh-release@v2
      if: ${{ github.event_name == 'release' }}
      with:
        files: ${{ inputs.treemap-output }}
      env:
        GITHUB_TOKEN: ${{ github.token }}