name: Example Gateway Configuration
server:
  host: 127.0.0.1
  port: 8080
  url: http://localhost:8080
management:
  prefix: _
  logging: true

routes:
  - name: Favicon
    from: /favicon.ico
    toFile: ./sample/webfiles/favicon.ico
    static: true
  - name: React App Assets
    from: /assets/*
    toFolder: ./webapp/dist/assets
    static: true
  - name: V1 of the API
    from: /api/v1/*
    removeFromPath: "/api/v1/"
    to: https://jsonplaceholder.typicode.com
  - name: V2 of the API (authenticated)
    from: /api/v2/*
    removeFromPath: "/api/v2/"
    to: https://jsonplaceholder.typicode.com
    authentication:
      enabled: true
  - name: httpbin
    from: /api/httpbin/*
    removeFromPath: "/api/httpbin/"
    to: http://localhost:8081
  - name: httpbin-auth
    from: /api/httpbin-auth/*
    removeFromPath: "/api/httpbin-auth/"
    to: http://localhost:8081
    authentication:
      enabled: true
  - name: Static files
    from: /static
    toFolder: ./sample/webfiles
    static: true
  - name: FrontEnd Authenticated
    from: /secret
    toFolder: ./sample/webfiles/secret
    static: true
    authentication:
      enabled: true
  - name: React App Index
    from: / # This will be the main catch-all for the React app
    toFile: ./webapp/dist/index.html
    static: true


authenticationProviders:
  basic:
    enabled: true
  google:
    clientId: ${GOOGLE_CLIENT_ID}
    clientSecret: ${GOOGLE_CLIENT_SECRET}
  github:
    clientId: ${GITHUB_CLIENT_ID}
    clientSecret: ${GITHUB_CLIENT_SECRET}

notification:
  email:
    enabled: true
    smtp:
      host: 127.0.0.1
      port: 1025
      username: ${SMTP_USERNAME}
      password: ${SMTP_PASSWORD}
      from: ${SMTP_FROM}
      fromName: ${SMTP_FROM_NAME}
