openapi: 3.0.0
info:
  title: Taronja Gateway API
  version: v1.0.0
  description: API for Taronja Gateway interal and public endpoints

paths:
  /health:
    get:
      summary: Health check
      operationId: healthCheck
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
  /login:
    # ...existing login code...
  /logout:
    # ...existing logout code...
  /me:
    get:
      summary: Get current logged user information
      operationId: getCurrentUser
      tags:
        - User
      security:
        - cookieAuth: []
      responses:
        '200':
          description: Information about the currently authenticated user
          content:
            application/json:
              schema:
                type: object
                properties:
                  authenticated:
                    type: boolean
                    example: true
                  username:
                    type: string
                    example: "testuser"
                  email:
                    type: string
                    format: email
                    example: "user@example.com"
                  provider:
                    type: string
                    example: "google"
                  timestamp:
                    type: string
                    format: date-time
                    example: "2023-01-01T12:00:00Z"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    HealthResponse:
      type: object
      properties:
        status:
          type: string
          example: "ok"
        timestamp:
          type: string
          format: date-time
          example: "2023-10-01T12:00:00Z"
      required:
        - status
        - timestamp
    Error:
      type: object
      properties:
        code:
          type: integer
          example: 401
        message:
          type: string
          example: "Unauthorized"
      required:
        - code
        - message
