name: Go Release

on:
  release:
    types: [published]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for GoReleaser to generate proper changelog

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: webapp/package-lock.json

      - name: Set up GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Optional: If you didn't add coverage-treemap.svg to extra_files in .goreleaser.yml,
      # you can upload it separately:
      - name: Upload coverage treemap to release
        uses: softprops/action-gh-release@v2
        with:
          files: coverage-treemap.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

